apiVersion: apps/v1
kind: Deployment
metadata:
  name: vidyo-k8s-service-deployment-v3
  labels:
    app: vidyo-k8s-service-v3
spec:
  replicas: 1
  selector:
    matchLabels:
        app: vidyo-k8s-service-v3
  template:
    metadata:
      labels:
        app: vidyo-k8s-service-v3
    spec:
      containers:
        - name: vidyo-k8s-service-v3
          image: sanjay10121985/vidyo-service
          ports:
            - containerPort: 8080